# Generated by Django 4.1.6 on 2023-02-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('bots_enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatServerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_run_at', models.DateTimeField(auto_now_add=True)),
                ('twitch_irc_address', models.CharField(default='irc.chat.twitch.tv', max_length=500)),
                ('twitch_irc_port', models.CharField(default=6667, max_length=500)),
                ('twitch_handle', models.CharField(default='your_twitch_user_name', max_length=500)),
                ('twitch_oauth_token', models.CharField(default='oauth:mibqh8j2e4zctqxavi8ypprkdmlptg', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Chat server settings',
            },
        ),
    ]
